#!/bin/bash

pidfile="bot.pid"

if [ -f $pidfile ]
then
    pid=$(cat $pidfile)
    if ps -p $pid > /dev/null
    then
       echo "$pid is running"
       kill $pid
    else
       echo "Not running"
    fi
    echo Found pid: $pid

    rm $pidfile
else
    echo No pid found
fi